// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/kittens.proto

package gomicro_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestEnvelope struct {
	ServiceMethod        string   `protobuf:"bytes,1,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Seq                  uint64   `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestEnvelope) Reset()         { *m = RequestEnvelope{} }
func (m *RequestEnvelope) String() string { return proto.CompactTextString(m) }
func (*RequestEnvelope) ProtoMessage()    {}
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9580523063d890, []int{0}
}

func (m *RequestEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestEnvelope.Unmarshal(m, b)
}
func (m *RequestEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestEnvelope.Marshal(b, m, deterministic)
}
func (m *RequestEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestEnvelope.Merge(m, src)
}
func (m *RequestEnvelope) XXX_Size() int {
	return xxx_messageInfo_RequestEnvelope.Size(m)
}
func (m *RequestEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_RequestEnvelope proto.InternalMessageInfo

func (m *RequestEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *RequestEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type ResponseEnvelope struct {
	ServiceMethod        string   `protobuf:"bytes,1,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	Seq                  uint64   `protobuf:"fixed64,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseEnvelope) Reset()         { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()    {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9580523063d890, []int{1}
}

func (m *ResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEnvelope.Unmarshal(m, b)
}
func (m *ResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *ResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEnvelope.Merge(m, src)
}
func (m *ResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_ResponseEnvelope.Size(m)
}
func (m *ResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEnvelope proto.InternalMessageInfo

func (m *ResponseEnvelope) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *ResponseEnvelope) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ResponseEnvelope) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9580523063d890, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9580523063d890, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestEnvelope)(nil), "gomicro.proto.RequestEnvelope")
	proto.RegisterType((*ResponseEnvelope)(nil), "gomicro.proto.ResponseEnvelope")
	proto.RegisterType((*Request)(nil), "gomicro.proto.Request")
	proto.RegisterType((*Response)(nil), "gomicro.proto.Response")
}

func init() { proto.RegisterFile("proto/kittens.proto", fileDescriptor_9d9580523063d890) }

var fileDescriptor_9d9580523063d890 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0xa9, 0xcf, 0xd7, 0xea, 0x40, 0xb5, 0x8c, 0xa2, 0x45, 0x14, 0x4a, 0x40, 0xe8, 0xaa,
	0x82, 0x6e, 0xdc, 0x8b, 0x20, 0x8a, 0x9b, 0xfc, 0x80, 0xd4, 0x3a, 0xd4, 0x62, 0x93, 0x69, 0x93,
	0xd8, 0xef, 0x97, 0x26, 0x71, 0x21, 0x2e, 0xdf, 0xee, 0x9e, 0x9b, 0x70, 0x18, 0x2e, 0x9c, 0x4c,
	0x86, 0x1d, 0xdf, 0x7c, 0x0d, 0xce, 0x91, 0xb6, 0x8d, 0x27, 0xcc, 0x7b, 0x56, 0x43, 0x67, 0x38,
	0xa0, 0x78, 0x86, 0x63, 0x49, 0xf3, 0x37, 0x59, 0xf7, 0xa8, 0x17, 0x1a, 0x79, 0x22, 0xbc, 0x86,
	0x23, 0x4b, 0x66, 0x19, 0x3a, 0x7a, 0x53, 0xe4, 0x3e, 0xf9, 0xa3, 0x4c, 0xaa, 0xa4, 0x3e, 0x94,
	0x79, 0x6c, 0x5f, 0x7d, 0x89, 0x05, 0x6c, 0x2c, 0xcd, 0xe5, 0x5e, 0x95, 0xd4, 0xa9, 0x5c, 0xa3,
	0x68, 0xa1, 0x90, 0x64, 0x27, 0xd6, 0x96, 0x76, 0x96, 0xe1, 0x29, 0x6c, 0xc9, 0x18, 0x36, 0xe5,
	0xc6, 0xff, 0x0f, 0x20, 0xae, 0x20, 0x8b, 0xe7, 0x22, 0xc2, 0xbe, 0x6e, 0x15, 0x45, 0x9f, 0xcf,
	0xe2, 0x12, 0x0e, 0x7e, 0x2f, 0x58, 0x95, 0xca, 0xf6, 0xf1, 0x79, 0x8d, 0xb7, 0x0f, 0x90, 0xbd,
	0x84, 0x2d, 0xf0, 0x1e, 0xb6, 0x4f, 0x34, 0x8e, 0x8c, 0x67, 0xcd, 0x9f, 0x3d, 0x9a, 0x68, 0xbf,
	0x38, 0xff, 0xd7, 0x07, 0xed, 0x7b, 0xea, 0xf9, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x5a,
	0x51, 0x66, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KittensClient is the client API for Kittens service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KittensClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type kittensClient struct {
	cc *grpc.ClientConn
}

func NewKittensClient(cc *grpc.ClientConn) KittensClient {
	return &kittensClient{cc}
}

func (c *kittensClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gomicro.proto.Kittens/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KittensServer is the server API for Kittens service.
type KittensServer interface {
	Hello(context.Context, *Request) (*Response, error)
}

// UnimplementedKittensServer can be embedded to have forward compatible implementations.
type UnimplementedKittensServer struct {
}

func (*UnimplementedKittensServer) Hello(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterKittensServer(s *grpc.Server, srv KittensServer) {
	s.RegisterService(&_Kittens_serviceDesc, srv)
}

func _Kittens_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KittensServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gomicro.proto.Kittens/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KittensServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kittens_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gomicro.proto.Kittens",
	HandlerType: (*KittensServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Kittens_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kittens.proto",
}
